<script setup lang="ts">
import { date, string } from 'yup'
import NForm from '~/components/NForm.vue'

const formRef = ref<InstanceType<typeof NForm>>()

const blueprint: Blueprint = reactive({
  form: {
    initialValues: async () => {},
    onSubmit: async (values) => {},
    onInvalidSubmit: async (errors) => {},
    header: {
      title: 'Form General',
      fields: {
        email: {
          type: 'text',
          label: 'Email',
          disabled: false,
          required: false,
          leadingIcon: 'i-heroicons-envelope',
          placeholder: 'someone@example.com',
          rules: string().email().required(),
          onChange: (value) => {
            blueprint.form.header.fields.username.value = value
          },
        },
        password: {
          type: 'text',
          label: 'Password',
          disabled: false,
          rules: string().required(),
          onChange: (value) => {},
        },
        username: {
          type: 'text',
          label: 'Username',
          disabled: false,
          rules: string().required(),
          value: '',
          onChange: (value) => {},
        },
        status: {
          type: 'select',
          label: 'Status',
          disabled: false,
          rules: string().required(),
          value: undefined,
          displayKey: 'label',
          valueKey: 'id',
          options: [
            { id: 1, label: 'Value 1' },
            { id: 1, label: 'Value 2' },
            { id: 1, label: 'Value 3' },
          ],
          onChange: (value) => {},
        },
        country: {
          type: 'asyncSelect',
          label: 'Country',
          disabled: false,
          value: 1,
          rules: string().required(),
          displayKey: 'name',
          valueKey: 'id',
          options: async () => [],
          onChange: (value) => {},
        },
        birthdate: {
          separator: '',
          type: 'date',
          label: 'Birthdate',
          disabled: false,
          value: new Date().toISOString(),
          rules: date().required(),
          onChange: (value) => {},
        },
        booking_date: {
          type: 'datetime',
          label: 'Booking Date',
          disabled: false,
          value: new Date().toISOString(),
          rules: date().required(),
          separator: '/',
          onChange: (value) => {},
        },
        sub_unit: {
          type: 'browse',
          label: 'Sub Unit',
          disabled: false,
          value: undefined,
          rules: string().required(),
          displayKey: 'value_1',
          valueKey: 'id',
          options: async () => [],
          onChange: (value) => {},
          fields: [
            { key: 'no', label: 'No' },
            { key: 'value_1', label: 'Value 1' },
            { key: 'value_2', label: 'Value 2' },
            { key: 'value_3', label: 'Value 3' },
          ],
        },
      },
    },
    detailMode: 'tabs',
    detail: [
      {
        title: 'Detail Form 1',
        mode: 'singular',
        fields: {
          text: {
            type: 'text',
            label: 'Text 1',
            disabled: false,
            rules: string().required(),
            onChange: (value) => {},
          },
          select: {
            type: 'select',
            label: 'Select 1',
            disabled: false,
            rules: string().required(),
            value: undefined,
            options: ['Value 1', 'Value 2', 'Value 3'],
            onChange: (value) => {},
          },
          async_select: {
            type: 'asyncSelect',
            label: 'Async Select 1',
            disabled: false,
            value: 1,
            displayKey: 'name',
            valueKey: 'id',
            rules: string().required(),
            options: async () => [],
            onChange: (value) => {},
          },
          date: {
            type: 'date',
            label: 'Date 1',
            disabled: false,
            value: new Date().toISOString(),
            rules: date().required(),
            onChange: (value) => {},
          },
          datetime: {
            type: 'datetime',
            label: 'DateTime 1',
            disabled: false,
            value: new Date().toISOString(),
            rules: date().required(),
            onChange: (value) => {},
          },
          browse: {
            type: 'browse',
            label: 'Browse 1',
            disabled: false,
            value: undefined,
            rules: string().required(),
            displayKey: 'value_1',
            valueKey: 'id',
            options: async () => [],
            onChange: (value) => {},
            fields: [
              { key: 'no', label: 'No', width: 'fit' },
              { key: 'value_1', label: 'Value 1', width: 10 },
              { key: 'value_2', label: 'Value 2', width: 10 },
              { key: 'value_3', label: 'Value 3', width: 10 },
            ],
          },
        },
      },
      {
        title: 'Detail Form 2',
        mode: 'multiple',
        fields: {
          text: {
            type: 'text',
            label: 'Text 2',
            disabled: false,
            rules: string().required(),
            onChange: (value) => {},
          },
          select: {
            type: 'select',
            label: 'Select 2',
            disabled: false,
            rules: string().required(),
            value: undefined,
            options: ['Value 1', 'Value 2', 'Value 3'],
            onChange: (value) => {},
          },
          async_select: {
            type: 'asyncSelect',
            label: 'Async Select 2',
            disabled: false,
            value: 1,
            displayKey: 'name',
            valueKey: 'id',
            rules: string().required(),
            options: async () => [],
            onChange: (value) => {},
          },
          date: {
            type: 'date',
            label: 'Date 2',
            disabled: false,
            value: new Date().toISOString(),
            rules: date().required(),
            onChange: (value) => {},
          },
          datetime: {
            type: 'datetime',
            label: 'DateTime 2',
            disabled: false,
            value: new Date().toISOString(),
            rules: date().required(),
            onChange: (value) => {},
          },
          browse: {
            type: 'browse',
            label: 'Browse 2',
            disabled: false,
            value: undefined,
            rules: string().required(),
            displayKey: 'value_1',
            valueKey: 'id',
            options: async () => [],
            onChange: (value) => {},
            fields: [
              { key: 'no', label: 'No', width: 'fit' },
              { key: 'value_1', label: 'Value 1', width: 10 },
              { key: 'value_2', label: 'Value 2', width: 10 },
              { key: 'value_3', label: 'Value 3', width: 10 },
            ],
          },
        },
      },
      {
        title: 'Detail Form 3',
        mode: 'selection',
        fields: {
          text: {
            type: 'text',
            label: 'Text 3',
            disabled: false,
            rules: string().required(),
            onChange: (value) => {},
          },
          select: {
            type: 'select',
            label: 'Select 3',
            disabled: false,
            rules: string().required(),
            value: undefined,
            options: ['Value 1', 'Value 2', 'Value 3'],
            onChange: (value) => {},
          },
          async_select: {
            type: 'asyncSelect',
            label: 'Async Select 3',
            disabled: false,
            value: 1,
            displayKey: 'name',
            valueKey: 'id',
            rules: string().required(),
            options: async () => [],
            onChange: (value) => {},
          },
          date: {
            type: 'date',
            label: 'Date 3',
            disabled: false,
            value: new Date().toISOString(),
            rules: date().required(),
            onChange: (value) => {},
          },
          datetime: {
            type: 'datetime',
            label: 'DateTime 3',
            disabled: false,
            value: new Date().toISOString(),
            rules: date().required(),
            onChange: (value) => {},
          },
          browse: {
            type: 'browse',
            label: 'Browse 3',
            disabled: false,
            value: undefined,
            rules: string().required(),
            displayKey: 'value_1',
            valueKey: 'id',
            options: async () => [],
            onChange: (value) => {},
            fields: [
              { key: 'no', label: 'No', width: 'fit' },
              { key: 'value_1', label: 'Value 1', width: 10 },
              { key: 'value_2', label: 'Value 2', width: 10 },
              { key: 'value_3', label: 'Value 3', width: 10 },
            ],
          },
        },
      },
    ],
  },
})
</script>

<template>
  <NForm ref="formRef" :blueprint="blueprint" />
</template>
